# This is a basic workflow to showcase the use of Reusable Workflows

name: Reusable Workflow
on:
  push:
    branches: 
      - dev
  pull_request:
    branches: 
      - dev
    types: [closed]
    
jobs:
  do-it:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: |
          echo Hello, from backend-service app !!
          
  docker:
    uses: supriyashevate/my-common-workflow/.github/workflows/docker-image.yml@master
    with:
      image_name: webapp
      tag: backend-service
    secrets:
      docker_username: ${{ secrets.DOCKER_USER }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
